wip: fix cloud units calculation
threefoldtech/tfexplorer pull request #223
Opened 2020-11-26 12:30 UTC by DylanVerstraete

2020-11-26 14:00 UTC, zaibon approved these changes

2020-11-27 08:37 UTC, muhamadazmy requested changes

2020-11-27 08:37 UTC, muhamadazmy commented on pkg/capacity/planner.go
> +func (p *NaivePlanner) updateUsedCapacityPool(poolID schema.ID) error {
Why you pass the pool id and then do a get, while u already have the object in the returned pools at line 584. wouldn't it be more efficient if u pass a pointer instead another db operation

2020-11-27 08:37 UTC, muhamadazmy commented on pkg/capacity/types/pool.go
> +	if err := cur.All(ctx, &out); err != nil {
This call is gonna be a killer if we have millions of pools. You should instead implement paging or streams. I would instead return a channel and go over the cursor item by item to end or until context is done.

2020-11-27 09:10 UTC, muhamadazmy approved these changes

2020-11-27 10:07 UTC, merged