Make a public ip reservation atomic swapable
threefoldtech/tfexplorer pull request #319
Opened 2021-05-28 07:18 UTC by DylanVerstraete

2021-05-28 08:32 UTC, muhamadazmy commented on pkg/directory/types/farm.go
> +	if err == nil {
That's a weird check, why not `if err != nil {return err}` instead of having this huge if statement!

2021-05-28 08:39 UTC, muhamadazmy requested changes
In general this looks good (except for the comments below and some code styling) but as far as I can see, this only "moves" the IP to a new reservation, but it does not decomission the older IP reservation. Once an older reservation is found, this reservation need to be also deprovisioned so the node takes the proper actions

2021-05-28 08:39 UTC, muhamadazmy commented on pkg/directory/types/farm.go
> +	if err != nil && !errors.Is(err, mongo.ErrNoDocuments) {
Why do u exclude the ErrNoDocuments error ?

2021-06-01 10:39 UTC, DylanVerstraete reviewed
Looks good :+1:

2021-06-01 10:58 UTC, xmonader approved these changes

2021-06-01 11:41 UTC, xmonader commented on pkg/workloads/reservation.go
> +			return mw.Conflict(fmt.Errorf("ip address already in use"))
can we add the ip address and the pool id in the error message please

2021-06-01 12:49 UTC, merged